"""
PURPOSE: Build synthetic notes at test-time using the REAL per-type
         templates from content-src/docs/.../_template/. Tests never copy
         template content; they read the live source.

OWNS:
  - Loading a type's templates from a real-content path
  - Filling placeholder values (CODE, NUMBER, DOMAIN, TAG)
  - Optionally mutating to introduce one specific defect
  - Writing the resulting index.{meta.json,mdx} to a tmp content root
  - Returning (meta_path, slug) so the test can address the note via the
    same slug the scanner derives

DESIGN:
  - Adding a new note type to rules.yaml + content-src/docs requires zero
    test edits — the factory discovers the template via rules.yaml
  - Adding a new folder to content-src/docs requires zero test edits —
    nothing here looks up specific slugs
"""

from __future__ import annotations

import json
import re
from datetime import date, timedelta
from pathlib import Path
from typing import Any


PLACEHOLDER_RE = re.compile(r"\{\{[A-Z_]+\}\}")


def _load_template(real_content_src: Path, rules_cfg: dict[str, Any], type_name: str) -> tuple[dict[str, Any], list[str], str]:
    """Return (meta_template_dict, heading_list, mdx_text) for a type."""
    note_types = rules_cfg["note_types"]
    if type_name not in note_types:
        raise KeyError(f"unknown type '{type_name}' (not in rules.yaml.note_types)")
    tdir = real_content_src / note_types[type_name]["template_dir"]
    meta_path = tdir / "example.meta.json.template"
    mdx_path = tdir / "example.mdx.template"
    if not meta_path.is_file():
        raise FileNotFoundError(f"missing template: {meta_path}")
    if not mdx_path.is_file():
        raise FileNotFoundError(f"missing template: {mdx_path}")
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    mdx_text = mdx_path.read_text(encoding="utf-8")
    headings = re.findall(r"^##\s+(.+?)\s*$", mdx_text, flags=re.MULTILINE)
    return meta, headings, mdx_text


def _resolve_placeholders(meta: dict[str, Any]) -> dict[str, Any]:
    """Replace {{X}} placeholders with deterministic test values."""
    repl = {
        "CODE": "TEST",
        "NUMBER": "0001",
        "DOMAIN": "TEST",
        "TAG": "test",
    }
    out: dict[str, Any] = {}
    for k, v in meta.items():
        if isinstance(v, str):
            new = v
            for token, value in repl.items():
                new = new.replace("{{" + token + "}}", value)
            out[k] = new
        elif isinstance(v, list):
            out[k] = [
                (PLACEHOLDER_RE.sub(lambda m: repl.get(m.group(0)[2:-2], m.group(0)), s) if isinstance(s, str) else s)
                for s in v
            ]
        else:
            out[k] = v
    return out


def _ensure_required_defaults(meta: dict[str, Any]) -> dict[str, Any]:
    """Fill empty mandatory scalars with valid placeholder values so the
    template baseline counts as a clean note."""
    if not meta.get("title"):
        meta["title"] = "Synthetic Test Note"
    if not meta.get("description"):
        meta["description"] = "Generated by tests/factory.py."
    if "last_reviewed" in meta and not meta["last_reviewed"]:
        meta["last_reviewed"] = date.today().isoformat()
    if "date_decided" in meta and not meta["date_decided"]:
        meta["date_decided"] = date.today().isoformat()
    if "date_started" in meta and not meta["date_started"]:
        meta["date_started"] = date.today().isoformat()
    return meta


def make_note(
    *,
    content_root: Path,
    real_content_src: Path,
    rules_cfg: dict[str, Any],
    type_name: str,
    folder_name: str,
    meta_overrides: dict[str, Any] | None = None,
    omit_meta_keys: list[str] | None = None,
    headings: list[str] | None = None,
) -> tuple[Path, str]:
    """
    Generate one note under content_root, derived from the real template
    for `type_name`. The note lives at:
        content_root / <template's parent folder-group path> / folder_name /
            index.meta.json
            index.mdx

    Returns (meta_path, scanner_slug).
    """
    meta, default_headings, _mdx_text = _load_template(real_content_src, rules_cfg, type_name)
    meta = _resolve_placeholders(meta)
    meta = _ensure_required_defaults(meta)
    if meta_overrides:
        meta.update(meta_overrides)
    for k in omit_meta_keys or []:
        meta.pop(k, None)

    template_dir_rel = Path(rules_cfg["note_types"][type_name]["template_dir"])
    parent_rel = template_dir_rel.parent
    note_dir = content_root / parent_rel / folder_name
    note_dir.mkdir(parents=True, exist_ok=True)

    use_headings = headings if headings is not None else default_headings
    mdx = "\n\n".join(f"## {h}" for h in use_headings) + ("\n" if use_headings else "")

    meta_path = note_dir / "index.meta.json"
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    (note_dir / "index.mdx").write_text(mdx, encoding="utf-8")

    slug_parts = [seg for seg in (parent_rel / folder_name).parts if not (seg.startswith("(") and seg.endswith(")"))]
    slug = "/".join(slug_parts)
    return meta_path, slug


def overdue_last_reviewed(rules_cfg: dict[str, Any], cycle: str, multiplier: float, today: date | None = None) -> str:
    """Return a YYYY-MM-DD string that is `multiplier` * window days in
    the past for the given cycle. Used by validator overdue tests."""
    today = today or date.today()
    window = rules_cfg["staleness_days"][cycle]
    days = int(window * multiplier) + 1
    return (today - timedelta(days=days)).isoformat()
