/**
 * PURPOSE: Sortable, filterable library registry table for the docs site.
 *
 * OWNS:
 *   - LibraryTable component (registered in mdx.tsx for use in MDX pages)
 *   - Client-side sorting via @tanstack/react-table
 *   - Section and type filtering via tag buttons
 *   - Text search on library name
 *
 * TOUCH POINTS:
 *   - Reads library-registry.data.json (generated by scripts/generate-lib-registry.ts)
 *   - Styled exclusively with Tailwind utilities using fd-* CSS custom properties
 *   - Registered in components/mdx.tsx
 *   - All visual overrides live in app/global.css
 */

'use client';

import { useState, useMemo } from 'react';
import {
  useReactTable,
  getCoreRowModel,
  getSortedRowModel,
  getFilteredRowModel,
  flexRender,
  createColumnHelper,
  type SortingState,
  type ColumnFiltersState,
} from '@tanstack/react-table';

import registryData from '@/content-src/docs/appendices/library-registry/library-registry.data.json';

interface LibraryEntry {
  number: number;
  name: string;
  section_id: string;
  section_title: string;
  function: string;
  tool_type: string;
  github_url: string;
  pypi_name: string | null;
  latest_version: string;
  last_updated: string;
  github_description: string;
  github_stars: number;
  github_license: string;
  pypi_summary: string;
  citation: string;
  pro: string;
  con: string;
  alternatives: string[];
  docs_tag: string | null;
  synced_at: string;
}

interface SectionEntry {
  id: string;
  title: string;
  goal: string;
  sort_order: number;
}

interface RegistryData {
  sections: SectionEntry[];
  libraries: LibraryEntry[];
}

const data = registryData as RegistryData;
const columnHelper = createColumnHelper<LibraryEntry>();

function formatDate(iso: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return '';
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  return `${mm}/${yyyy}`;
}

function SortIcon({ direction }: { direction: false | 'asc' | 'desc' }) {
  if (!direction) {
    return <span className="ml-1 text-fd-muted-foreground/40">&#8597;</span>;
  }
  return (
    <span className="ml-1 text-fd-primary">
      {direction === 'asc' ? '\u2191' : '\u2193'}
    </span>
  );
}

export function LibraryTable() {
  const [sorting, setSorting] = useState<SortingState>([]);
  const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);
  const [globalFilter, setGlobalFilter] = useState('');
  const [activeSection, setActiveSection] = useState<string | null>(null);
  const [activeType, setActiveType] = useState<string | null>(null);

  const toolTypes = useMemo(
    () => [...new Set(data.libraries.map((l) => l.tool_type))].sort(),
    [],
  );

  const filteredData = useMemo(() => {
    let libs = data.libraries;
    if (activeSection) {
      libs = libs.filter((l) => l.section_id === activeSection);
    }
    if (activeType) {
      libs = libs.filter((l) => l.tool_type === activeType);
    }
    return libs;
  }, [activeSection, activeType]);

  const columns = useMemo(
    () => [
      columnHelper.accessor('number', {
        header: '#',
        cell: (info) => info.getValue(),
        size: 50,
      }),
      columnHelper.accessor('name', {
        header: 'Name',
        cell: (info) => {
          const row = info.row.original;
          const desc = row.github_description || row.pypi_summary || '';
          return (
            <a
              href={row.github_url}
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-fd-primary hover:underline"
              title={desc}
            >
              {info.getValue()}
            </a>
          );
        },
        size: 160,
      }),
      columnHelper.accessor('function', {
        header: 'Function',
        cell: (info) => info.getValue(),
        size: 200,
      }),
      columnHelper.accessor('github_stars', {
        header: 'Stars',
        cell: (info) => {
          const v = info.getValue();
          if (!v) return <span className="text-fd-muted-foreground">--</span>;
          return <span className="tabular-nums">{v.toLocaleString()}</span>;
        },
        size: 80,
      }),
      columnHelper.accessor('tool_type', {
        header: 'Type',
        cell: (info) => (
          <span className="inline-block rounded-md bg-fd-secondary px-2 py-0.5 text-xs text-fd-secondary-foreground">
            {info.getValue()}
          </span>
        ),
        size: 100,
      }),
      columnHelper.accessor('latest_version', {
        header: 'Version',
        cell: (info) => {
          const v = info.getValue();
          return v ? (
            <code className="text-xs">{v}</code>
          ) : (
            <span className="text-fd-muted-foreground">--</span>
          );
        },
        size: 100,
      }),
      columnHelper.accessor('last_updated', {
        header: 'Updated',
        cell: (info) => {
          const formatted = formatDate(info.getValue());
          return formatted || (
            <span className="text-fd-muted-foreground">--</span>
          );
        },
        sortingFn: 'datetime',
        size: 120,
      }),
      columnHelper.accessor('section_title', {
        header: 'Section',
        cell: (info) => (
          <span className="text-xs text-fd-muted-foreground">
            {info.getValue()}
          </span>
        ),
        size: 180,
      }),
    ],
    [],
  );

  const table = useReactTable({
    data: filteredData,
    columns,
    state: { sorting, columnFilters, globalFilter },
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    onGlobalFilterChange: setGlobalFilter,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    globalFilterFn: 'includesString',
  });

  return (
    <div className="not-prose">
      {/* Search and filter controls */}
      <div className="mb-4 flex flex-col gap-3">
        <input
          type="text"
          placeholder="Search libraries..."
          value={globalFilter}
          onChange={(e) => setGlobalFilter(e.target.value)}
          className="w-full rounded-lg border border-fd-border bg-fd-background px-3 py-2 text-sm text-fd-foreground placeholder:text-fd-muted-foreground focus:outline-none focus:ring-2 focus:ring-fd-ring sm:max-w-xs"
        />

        {/* Section filter */}
        <div className="flex flex-wrap gap-1.5">
          <button
            onClick={() => setActiveSection(null)}
            className={`rounded-md px-2.5 py-1 text-xs transition-colors ${
              activeSection === null
                ? 'bg-fd-primary text-fd-primary-foreground'
                : 'bg-fd-secondary text-fd-secondary-foreground hover:bg-fd-accent'
            }`}
          >
            All Sections
          </button>
          {data.sections.map((sec) => (
            <button
              key={sec.id}
              onClick={() =>
                setActiveSection(activeSection === sec.id ? null : sec.id)
              }
              className={`rounded-md px-2.5 py-1 text-xs transition-colors ${
                activeSection === sec.id
                  ? 'bg-fd-primary text-fd-primary-foreground'
                  : 'bg-fd-secondary text-fd-secondary-foreground hover:bg-fd-accent'
              }`}
            >
              {sec.title}
            </button>
          ))}
        </div>

        {/* Type filter */}
        <div className="flex flex-wrap gap-1.5">
          <button
            onClick={() => setActiveType(null)}
            className={`rounded-md px-2.5 py-1 text-xs transition-colors ${
              activeType === null
                ? 'bg-fd-primary text-fd-primary-foreground'
                : 'bg-fd-secondary text-fd-secondary-foreground hover:bg-fd-accent'
            }`}
          >
            All Types
          </button>
          {toolTypes.map((type) => (
            <button
              key={type}
              onClick={() =>
                setActiveType(activeType === type ? null : type)
              }
              className={`rounded-md px-2.5 py-1 text-xs transition-colors ${
                activeType === type
                  ? 'bg-fd-primary text-fd-primary-foreground'
                  : 'bg-fd-secondary text-fd-secondary-foreground hover:bg-fd-accent'
              }`}
            >
              {type}
            </button>
          ))}
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto rounded-xl border border-fd-border">
        <table className="w-full text-sm">
          <thead>
            {table.getHeaderGroups().map((headerGroup) => (
              <tr key={headerGroup.id} className="border-b border-fd-border bg-fd-muted">
                {headerGroup.headers.map((header) => (
                  <th
                    key={header.id}
                    className="cursor-pointer select-none px-3 py-2.5 text-left text-xs font-medium text-fd-muted-foreground"
                    style={{ width: header.getSize() }}
                    onClick={header.column.getToggleSortingHandler()}
                  >
                    <span className="flex items-center">
                      {flexRender(
                        header.column.columnDef.header,
                        header.getContext(),
                      )}
                      <SortIcon
                        direction={header.column.getIsSorted()}
                      />
                    </span>
                  </th>
                ))}
              </tr>
            ))}
          </thead>
          <tbody>
            {table.getRowModel().rows.map((row) => (
              <tr
                key={row.id}
                className="border-b border-fd-border transition-colors last:border-b-0 hover:bg-fd-accent/50"
              >
                {row.getVisibleCells().map((cell) => (
                  <td key={cell.id} className="px-3 py-2 text-fd-foreground">
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </td>
                ))}
              </tr>
            ))}
            {table.getRowModel().rows.length === 0 && (
              <tr>
                <td
                  colSpan={columns.length}
                  className="px-3 py-8 text-center text-fd-muted-foreground"
                >
                  No libraries match the current filters.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Count */}
      <p className="mt-2 text-xs text-fd-muted-foreground">
        Showing {table.getRowModel().rows.length} of{' '}
        {data.libraries.length} libraries
        {filteredData.length !== data.libraries.length && ' (filtered)'}
      </p>
    </div>
  );
}
